"""SciForge: the Fusion-style interface layer of the SciForge fork of FreeCAD.

This package must stay importable outside FreeCAD (the *_core modules are
pure Python and are unit tested), so nothing here imports FreeCAD or Qt at
module level except inside the logging helpers.
"""

import os

__version__ = "0.2.0"
ROOT = os.path.dirname(os.path.abspath(__file__))


def icon_path(name):
    return os.path.join(ROOT, "icons", name)


def ui_icon_path(name):
    """Path of a ribbon/menu icon generated by tools/sciforge/make_icons.py."""
    return os.path.join(ROOT, "icons", "ui", name + ".svg")


_ICON_CACHE = {}


def ui_icon(name):
    """QIcon for a ribbon/menu icon (empty icon if name is None or missing)."""
    from .compat import QtGui

    if not name:
        return QtGui.QIcon()
    if name not in _ICON_CACHE:
        path = ui_icon_path(name)
        if not os.path.isfile(path):
            warn("missing icon %s" % name)
            path = ui_icon_path("not_available")
        _ICON_CACHE[name] = QtGui.QIcon(path)
    return _ICON_CACHE[name]


# The last SciForge messages, shown (copyable) in SciForge > Diagnostics: FreeCAD's
# own error pop-ups fade away before they can be copied.
RECENT = []
RECENT_MAX = 200


def _remember(kind, msg):
    import time

    RECENT.append("%s %s %s" % (time.strftime("%H:%M:%S"), kind, msg))
    del RECENT[:-RECENT_MAX]


def _console():
    try:
        import FreeCAD

        return FreeCAD.Console
    except ImportError:
        return None


def log(msg):
    _remember("info", msg)
    console = _console()
    if console:
        console.PrintMessage("[SciForge] %s\n" % msg)
    else:
        print("[SciForge] %s" % msg)


def warn(msg):
    _remember("WARNING", msg)
    console = _console()
    if console:
        console.PrintWarning("[SciForge] %s\n" % msg)
    else:
        print("[SciForge] WARNING: %s" % msg)
